import { Link } from "react-router-dom";
import { Container } from "@/components/atoms/Container";
import logo from "@/assets/sunavio-logo-white.png";

const solutionLinks = [["Photovoltaïque en autoconsommation","/solutions#autoconsommation"],["Stockage par batteries","/solutions#stockage"],["Micro-réseaux et sites isolés","/solutions#micro-reseaux"],["Pompage solaire","/agriculture-pompage-solaire"],["Résidentiel premium","/panneaux-solaires-villa-marrakech"],["Kits piscine","/kits-piscine"]];
const sectorLinks = [["Industrie","/panneaux-solaires-industrie-maroc"],["Hôtellerie","/panneaux-solaires-hotel-marrakech"],["Golf","/panneaux-solaires-golf-maroc"],["Agriculture","/agriculture-pompage-solaire"],["Infrastructures","/contact"]];
const companyLinks = [["À propos","/a-propos"],["Références","/references"],["Ressources","/ressources"],["Contact","/contact"],["Mentions légales","/mentions-legales"],["Confidentialité","/confidentialite"],["CGU","/cgu"],["Cookies","/cookies"]];

const Links = ({title, items}:{title:string;items:string[][]}) => <div><h3 className="text-sm font-semibold text-bg">{title}</h3><ul className="mt-5 space-y-3">{items.map(([label,to]) => <li key={label}><Link to={to} className="text-sm text-bg/70 hover:text-or">{label}</Link></li>)}</ul></div>;

export function Footer() { return <footer className="bg-wh pb-20 text-bg md:pb-0"><Container size="wide" className="py-14 md:py-20"><div className="grid gap-12 md:grid-cols-2 lg:grid-cols-4"><div><img src={logo} alt="SUNAVIO" className="h-9 w-auto"/><p className="mt-5 text-sm leading-7 text-bg/70">SUNAVIO SARL<br/>Zenith Business Center, Bab Doukala<br/>Marrakech, Maroc</p><a className="mt-4 block text-sm text-bg" href="tel:+212663284424">+212 6 63 28 44 24</a><a className="mt-2 block text-sm text-bg" href="mailto:contact@sunavio.com">contact@sunavio.com</a><p className="mt-5 text-sm font-semibold text-or">L'excellence solaire</p></div><Links title="Solutions" items={solutionLinks}/><Links title="Secteurs" items={sectorLinks}/><Links title="Entreprise" items={companyLinks}/></div><div className="mt-14 flex flex-col gap-3 border-t border-bg/20 pt-6 text-xs text-bg/60 md:flex-row md:justify-between"><span>Installateur certifié Huawei Smart PV — FusionSolar Certified Installer</span><span>© 2026 SUNAVIO SARL</span></div></Container></footer>; }