import { Link, Navigate, useParams } from "react-router-dom";
import { IndustrialPage, Section } from "@/components/industrial/IndustrialPage";
import { SunavioButton } from "@/components/atoms/SunavioButton";

const articles: Record<string,{title:string;intro:string;sections:{title:string;text:string}[];takeaway:string}> = {
  "loi-82-21-autoproduction": { title:"Loi 82-21 : ce qui change pour un industriel", intro:"La loi structure l'autoproduction électrique et clarifie le cadre dans lequel un site professionnel peut produire pour ses propres besoins.", takeaway:"Le point de départ reste le même : profil de charge, tension de raccordement et scénario d'exploitation doivent être documentés avant le dépôt du dossier.", sections:[{title:"Un cadre pour produire et consommer sur site",text:"Le projet photovoltaïque est dimensionné en priorité pour la consommation du site. Le régime applicable dépend notamment de la puissance, du niveau de tension et du gestionnaire de réseau."},{title:"Une étude technique avant la démarche administrative",text:"L'unifilaire, les protections, le contrôle d'injection et le comportement de la centrale en cas de défaut doivent être définis. La note de calcul sert à éviter une demande incomplète ou une centrale mal dimensionnée."},{title:"Une coordination avec le gestionnaire",text:"SUNAVIO prépare le dossier et coordonne les échanges techniques avec la SRM ou l'ONEE selon la localisation et le raccordement du site."}]},
  "zero-injection": { title:"Zéro injection ou injection limitée : comment choisir ?", intro:"Le choix dépend du profil de charge, du cadre de raccordement et de la quantité de surplus que le site peut réellement valoriser.", takeaway:"Un dispositif de zéro injection fiable combine mesure, régulation et protection indépendante ; un simple réglage logiciel ne suffit pas.", sections:[{title:"1. Mesure et régulation",text:"Un compteur au point de livraison transmet la puissance échangée au contrôleur, qui ajuste instantanément les onduleurs."},{title:"2. Repli fail-safe",text:"En cas de perte de mesure ou de communication, la centrale revient automatiquement vers un état sûr défini lors de l'étude."},{title:"3. Protection indépendante",text:"Un relais de retour de puissance peut commander le disjoncteur photovoltaïque selon les prescriptions du gestionnaire de réseau."}]},
  "stockage-batteries-industrie": { title:"Quand une batterie est-elle rentable sur un site industriel ?", intro:"Une batterie doit résoudre un problème chiffré. Sa valeur dépend du tarif, du surplus photovoltaïque, de la puissance appelée et des contraintes du process.", takeaway:"La simulation doit croiser la charge du site, la production photovoltaïque et l'état de charge de la batterie à un pas horaire ou infra-horaire.", sections:[{title:"Écrêter les périodes coûteuses",text:"La batterie peut décaler l'énergie vers les heures de pointe lorsque l'écart tarifaire couvre ses pertes et son vieillissement."},{title:"Valoriser un surplus récurrent",text:"Sur un site fermé le week-end ou soumis à de fortes variations, le stockage peut absorber une part de production autrement limitée."},{title:"Sécuriser un process ciblé",text:"Pour certaines charges critiques, une architecture formant réseau peut compléter les protections existantes. Elle ne remplace pas une étude de sélectivité et de continuité."}]}
};
const ResourceArticle=()=>{const {slug}=useParams(); const article=slug?articles[slug]:undefined; if(!article)return <Navigate to="/ressources" replace/>; return <IndustrialPage path={`/ressources/${slug}`} eyebrow="RESSOURCE TECHNIQUE" title={article.title} intro={article.intro}><Section title="Analyse"> <article className="max-w-3xl space-y-10">{article.sections.map(s=><section key={s.title}><h2 className="text-2xl font-semibold text-wh">{s.title}</h2><p className="mt-3 leading-8 text-gr2">{s.text}</p></section>)}<div className="info-panel"><strong>À retenir — </strong>{article.takeaway}</div><SunavioButton asChild size="lg"><Link to="/pre-etude">Demander une pré-étude</Link></SunavioButton></article></Section></IndustrialPage>};
export default ResourceArticle;