import { Link } from "react-router-dom";
import { IndustrialPage, Section, CardGrid, FinalCTA } from "@/components/industrial/IndustrialPage";

const Solutions = () => <IndustrialPage path="/solutions" eyebrow="SOLUTIONS" title="Nos solutions photovoltaïques pour les sites professionnels" intro="De la note de calcul à l'exploitation, SUNAVIO conçoit une architecture adaptée au profil électrique, au foncier et aux contraintes de chaque site.">
  <Section id="autoconsommation" title="Photovoltaïque en autoconsommation" intro="Trois implantations principales, sélectionnées après relevé du site."><div className="overflow-x-auto"><table className="technical-table"><thead><tr><th>Implantation</th><th>Quand la retenir</th><th>Puissance typique</th><th>Points clés</th></tr></thead><tbody><tr><td>Toiture bac acier</td><td>Grande surface disponible au plus près du TGBT</td><td>100 kWc à 1 MWc</td><td>Rapport de structure, fixation sans percement ou lestage, sécurité anti-chute</td></tr><tr><td>Ombrières</td><td>Parking ou aire logistique à valoriser</td><td>50 à 500 kWc</td><td>Double usage, acier galvanisé, hauteur libre adaptée aux engins</td></tr><tr><td>Champ au sol</td><td>Réserve foncière et besoin de forte puissance</td><td>500 kWc à plusieurs MWc</td><td>Modules bifaciaux, poste élévateur si MT/HTA, étude géotechnique</td></tr></tbody></table></div></Section>
  <Section id="stockage" alt title="Stockage par batteries" intro="Le stockage répond à un usage mesurable : il n'est jamais ajouté par principe."><CardGrid items={[{title:"Écrêtage tarifaire",description:"Décalage de l'énergie vers la plage 17 h – 22 h lorsque la structure tarifaire le justifie."},{title:"Absorption du surplus",description:"Conservation de la production qui ne peut pas être consommée ou injectée."},{title:"Puissance souscrite",description:"Lissage des appels de puissance et réduction des dépassements."},{title:"Process critique",description:"Sécurisation ciblée en mode formateur de réseau lorsque l'architecture le permet."}]}/><div className="info-panel mt-8"><strong>Position SUNAVIO — </strong>Le stockage n'est proposé que lorsqu'une simulation horaire couplée PV + charge + état de charge démontre sa valeur. Nos centrales peuvent être livrées prêtes pour une phase ultérieure.</div></Section>
  <Section id="micro-reseaux" title="Micro-réseaux, sites isolés et pompage"><CardGrid items={[{title:"Micro-réseaux",description:"Pilotage coordonné du photovoltaïque, des batteries et du groupe électrogène pour les sites éloignés du réseau."},{title:"Pompage solaire",description:"Forages, bassins et irrigation dimensionnés selon les besoins hydrauliques et les périodes de fonctionnement."},{title:"Mobilité électrique",description:"Recharge de véhicules et d'engins intégrée à la stratégie énergétique du site."}]}/></Section>
  <Section alt title="Résidentiel premium" intro="Notre cœur de métier est industriel. Nous accompagnons toutefois un nombre limité de villas et domaines à Marrakech."><div className="flex flex-wrap gap-4"><Link className="font-semibold text-or" to="/panneaux-solaires-villa-marrakech">Solutions pour villas →</Link><Link className="font-semibold text-or" to="/kits-piscine">Kits piscine →</Link><a className="font-semibold text-or" href="https://estimer.sunavio.com">Estimateur résidentiel →</a></div></Section>
  <Section title="Services associés"><div className="overflow-x-auto"><table className="technical-table"><thead><tr><th>Service</th><th>Livrable</th></tr></thead><tbody>{[["Audit et pré-étude","Note de calcul, variantes et budget estimatif"],["Étude détaillée APD","Simulation, plans, schémas et quantitatifs"],["Dossier réglementaire","Pièces de raccordement et coordination gestionnaire"],["Réalisation clé en main","Fourniture, montage, protections et essais"],["Exploitation et maintenance","Supervision, maintenance et bilan annuel"],["Programme multi-sites","Architecture standardisée et pilotage consolidé"]].map(r=><tr key={r[0]}><td>{r[0]}</td><td>{r[1]}</td></tr>)}</tbody></table></div></Section><FinalCTA/>
</IndustrialPage>;
export default Solutions;